### ISSUE TITLE
Call handleHide() when a user clicks outside the popover

### ISSUE THREAD

**Issue by mo0om** [ciena-frost/ember-frost-popover#76]
## Summary

![image](https://user-images.githubusercontent.com/1723490/39587395-632f7f16-4ec7-11e8-90a7-9a5171a48acf.png)

if the user clicks beside the popover, the popover closes but the function `handleHide()` is never called. 

## Motivation
There are occasions where this behavior is viable but in some other used case, `handleHide()` should be call onClose of the popover.

## Detailed design
Just passing an extra switch like `handleHideOnClose=true` on this component and then ...
```
closePopover (event) {
    let popover = this.get('element')
    if ($(event.target).closest(popover).length === 0) {
      this.get('showDelayTask').cancelAll()
      this.set('visible', false)
      this.unregisterClickOff()
      if (this.get('handleHideOnClose')) {
         this.handleHide()
      }
    }
  },
```

**Comment by notmessenger** [comment]
I think there's a better way to handle this and still achieve what is desired but I do not have the time at the moment to dig into it fully.  Whoever addresses this issue please reach out to me for a quick discussion before proceeding.

**Comment by notmessenger** [comment]
Basically the approach I am thinking of is that `handleHide()` is only called when the button is toggled again, for all example usages in the demo app, and not when the user clicks off of the button or tooltip and it closes.  If both actions result in the visual removal of the tooltip why are we treating one action (clicking the control again) as more of a close than another one (clicking elsewhere off of the control)?  Why does one close method do more than the other?   If we fix this(*) overall it fixes it for every scenario, including the one you opened this issue about, and we don't need to introduce an additional property to opt into this behavior.

* Fix denotes that it's broken.  Perhaps we actually want this difference in behavior, even though it seems odd to me.  That will need to be determined first.

**Comment by pbosse** [comment]
I understand your concern here.  Who will determine this though? UX? 
I am getting a bit concern that this will take time, and it's time we cannot afford at this moment as this fix is needed for the Custom Alert feature we have to deliver by may 25th.
Is there anything we can do to accelerate this?  Right now a PR is blocked because this issue isn't fixed. I realize there is a lot of pressure from everywhere but I just want to make sure it is address ASAP.

**Comment by mo0om** [comment]
Hey guys, I found a way around this issue therefore there is no rush on my side to fix it. Nevertheless I think this is a problem that should be addressed eventually. Let me know if you need my help to fix it.

**Comment by notmessenger** [comment]
UX would certainly need to be consulted.  My preference is that we address this in a more-correct manner rather than the way proposed in https://github.com/ciena-frost/ember-frost-popover/pull/79 but if it is decided to merge this PR anyway please open an issue so that we can fix this in the future.

**Comment by mo0om** [comment]
What if I just modify the PR that's already there to just add `handleHide` and remove the extra switch `handleHideOnClose=true `?
```
closePopover (event) {
    let popover = this.get('element')
    if ($(event.target).closest(popover).length === 0) {
      this.get('showDelayTask').cancelAll()
      this.set('visible', false)
      this.unregisterClickOff()
      this.handleHide()     
    }
  },
```

**Comment by notmessenger** [comment]
I do like the removal of the flag.   Does this provide a consistent behavior in all demonstrated usages though or is the "Toggle Function" example the only one impacted?  Because if the latter then I question whether having the flag becomes more correct so it's more known/obvious what behavior you're going to get... :-/

**Comment by notmessenger** [comment]
We could remove the flag and still keep the "Toggle function" example, because if we always call `handleHide()` then we're good to go regardless.

**Comment by mo0om** [comment]
you're right. I'll make another PR.
